-- SPDX-License-Identifier: AGPL-3.0-or-later
-- Generated by scripts/generate-plan-catalogue.mjs; existing customer overrides remain intact.
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('free','agents',3) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('free','tasks_per_month',50) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('free','teams',1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('free','members',1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('free','triggers',1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('free','knowledge_documents',3) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('free','marketplace_installs',-1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('pro','agents',25) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('pro','tasks_per_month',1000) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('pro','teams',10) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('pro','members',3) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('pro','triggers',10) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('pro','knowledge_documents',25) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('pro','marketplace_installs',-1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('team','agents',-1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('team','tasks_per_month',10000) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('team','teams',-1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('team','members',25) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('team','triggers',-1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('team','knowledge_documents',-1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('team','marketplace_installs',-1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('enterprise','agents',-1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('enterprise','tasks_per_month',-1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('enterprise','teams',-1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('enterprise','members',-1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('enterprise','triggers',-1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('enterprise','knowledge_documents',-1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
INSERT INTO public.plan_limits(plan,resource,max_value) VALUES('enterprise','marketplace_installs',-1) ON CONFLICT(plan,resource) DO UPDATE SET max_value=EXCLUDED.max_value;
CREATE OR REPLACE FUNCTION public.features_for_plan(p_plan text) RETURNS text[] LANGUAGE sql IMMUTABLE SET search_path='' AS $$ SELECT CASE p_plan
WHEN 'free' THEN ARRAY['orchestrator_mode','marketplace_publish','a2a_publish','chat_widget']::text[]
WHEN 'pro' THEN ARRAY['orchestrator_mode','marketplace_publish','a2a_publish','chat_widget','prompt_history','advanced_analytics','file_attachments','advanced_webhooks','team_triggers','billing','messaging_channels','custom_tools']::text[]
WHEN 'team' THEN ARRAY['orchestrator_mode','marketplace_publish','a2a_publish','chat_widget','prompt_history','advanced_analytics','file_attachments','advanced_webhooks','team_triggers','billing','messaging_channels','custom_tools','collaboration_mode','team_memory','rbac']::text[]
WHEN 'enterprise' THEN ARRAY['orchestrator_mode','marketplace_publish','a2a_publish','chat_widget','prompt_history','advanced_analytics','file_attachments','advanced_webhooks','team_triggers','billing','messaging_channels','custom_tools','collaboration_mode','team_memory','rbac','audit_logs','swarm','admin_panel']::text[]
ELSE ARRAY[]::text[] END $$;
